### ISSUE TITLE
this.modalDragService.confirm({nzTitle: 'Confirm', nzContent: '提示一下的内容'})拿不到返回值

### ISSUE THREAD

**Issue by wen2204** [huajian123/ng-ant-admin#15]
弹出的确认框需要知道确认的结果，是点击了确定，还是取消
```
 const dialog=this.modalDragService.confirm({nzTitle: 'Confirm', nzContent: '提示一下的内容'})
 dialog.afterClose.subscribe(result => {
      console.log(result);})
```
这个返回的值是undefine，这样没法判断是点击了确定，还是取消，有什么办法可以确定弹出的模态框点击了什么按钮么？

**Comment by huajian123** [comment]
@wen2204     this.modalDragService.confirm({
      nzTitle: 'Confirm', nzContent: '提示一下的内容', nzOnOk: () => {
        console.log('确定');
      },
      nzOnCancel:()=>{
        console.log('取消');
      }
    })

**Comment by wen2204** [comment]
非常感谢
