### ISSUE TITLE
在发布之后，手机端浏览器浏览时，导航菜单字体变成黑色

### ISSUE THREAD

**Issue by wen2204** [huajian123/ng-ant-admin#16]
电脑端浏览正常，手机端浏览菜单的字体颜色变成暗色，点击字体发现恢复。
![示例](https://user-images.githubusercontent.com/37831325/167418279-3d9fc4d6-5078-46dd-9f6f-effd80034976.jpg)

**Comment by wen2204** [comment]
在华为鸿蒙系统上，华为自带的浏览器和QQ浏览器均是这样。电脑端模拟没有这个问题，可能是手机浏览器兼容性问题。

**Comment by huajian123** [comment]
是的。手机上使用chrome浏览器即可

**Comment by wen2204** [comment]
thank you very much
