### ISSUE TITLE
作者大大好

### ISSUE THREAD

**Issue by lixinliA** [huajian123/ng-ant-admin#18]
我是vue转angular,看了您这个项目感觉很有学习价值,由于对angular不熟练,看完您的视频后,对项目中rxjs的用法还是不懂,您有时间可不可以录个项目中rxjs的教学视频,再次感谢

**Comment by huajian123** [comment]
@lixinliA Hi，您可以通过 https://blog.jerry-hong.com/series/rxjs/
https://v7.rxjs.tech/
进行学习，如果您有疑问可以加入qq群 376065816 进行讨论
