### ISSUE TITLE
auth0/angular-jwt 已经关闭了，建议使用目前还在维护的库

### ISSUE THREAD

**Issue by wen2204** [huajian123/ng-ant-admin#22]
[angular-jwt](https://github.com/auth0/angular-jwt)

Warning This repository has been archived, the libaray has been deprecated, but remains available on NPM.

**Comment by huajian123** [comment]
Thank you，好的

**Comment by huajian123** [comment]
@wen2204 hi ，请将"@auth0/angular-jwt": "^5.1.0",升级至5.1.0版本，作者在https://github.com/auth0/angular2-jwt/issues/712中已经将这个问题修复，有任何疑问请重新打开这个issues
