### ISSUE TITLE
Token的过期以及refresh问题

### ISSUE THREAD

**Issue by wen2204** [huajian123/ng-ant-admin#23]
Token的过期是靠后端反馈(如果我没有看错的话)，token是直接在前端可以判断出是否过期的，从请求后再去判断过期，不太合理。此外，也没有看到refresh token的操作

**Comment by huajian123** [comment]
@wen2204 hi,如果你长期在一个列表页面长达1小时（此时token过期），然后点击新增按钮（此时未调用任何其他接口），弹出新增表单窗口，让你填写表单内容，填写完成之后，点击提交按钮，调用提交接口，因为token过期，会弹出登录窗口，让你登录，你登录完成之后，之前的新增接口会继续再调用一次。如果你登录失败，则直接跳转到登录页，新增接口也不会调用。这是ng-ant-admin处理token过期的逻辑，如果您有疑问，可以重新打开此issues
