### ISSUE TITLE
DatePicker日期选择框样式错乱

### ISSUE THREAD

**Issue by wenzqbaby** [huajian123/ng-ant-admin#25]
日期选择框弹出日期面板样式错乱
![GO53(JV4}OW{_3S~)GFC8ED](https://user-images.githubusercontent.com/28187003/197915929-6d8afb46-7d34-4ef9-8556-7535e4a8e7c9.png)

**Comment by huajian123** [comment]
@wenzqbaby 请删除minireset.less 我将在下次更新时将其删除

**Comment by wenzqbaby** [comment]
我尝试在base.less中添加样式

**Comment by wenzqbaby** [comment]
我尝试在base.less添加如下样式: 
![HY1{_YDK{{H6MGT$RS)VLM](https://user-images.githubusercontent.com/28187003/198009827-dca09602-1188-412a-bc8d-24b2ad43be10.png)
这能暂时解决我的问题, 但是删除minireset.less是更好的解决方法
thank you.

**Comment by huajian123** [comment]
谢谢

**Comment by huajian123** [comment]
@wenzqbaby 这个文件是有必要的，我又重新加了回来，但是删除了td:not([align]),
th:not([align]) 相关样式
