### ISSUE TITLE
use of wrong pattern to get variable value

### ISSUE THREAD

**Issue by factorx22** [huajian123/ng-ant-admin#30]
In src/app/core/services/common/reuse-strategy.ts

// 是否允许复用路由
  shouldDetach(route: ActivatedRouteSnapshot): boolean {
    // 是否展示多页签，如果不展示多页签，则不做路由复用
    **let isShowTab = false;
    this.isShowTab$.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(res => {
      isShowTab = res.isShowTab;
    });**
    return route.data['shouldDetach'] !== 'no' && isShowTab;
  }

This is a pattern for synchronous execution, but using subscribe on an observable results in asynchronous execution. The value of the variable isShowTab when evaluating the condition (return route.data['shouldDetach'] !== 'no' && isShowTab;) may not be as expected

Consider using :

  // 是否有多页签，没有多页签则不做路由缓存
  isShowTab$ = inject(ThemeStoreService);
.
.
.
  shouldDetach(route: ActivatedRouteSnapshot): boolean {
    // 是否展示多页签，如果不展示多页签，则不做路由复用
    let isShowTab = this.isShowTab$.getCurrentThemesMode().isShowTab;
    return route.data['shouldDetach'] !== 'no' && isShowTab;
  }
.
.
.
.
adding to theme-store.service :

  getCurrentThemesMode(): SettingInterface {
    return this.themesMode$.getValue();
  }

**Comment by huajian123** [comment]
@factorx22 Thank you very much for your issue. In my understanding, rxjs can be executed synchronously in this way. Maybe your way might be easier to understand. If you have any questions, please continue to discuss with me。
<img width="883" alt="image" src="https://github.com/huajian123/ng-ant-admin/assets/31737260/f36349ed-d9e3-4d46-a93d-d1394b2cfa48">
<img width="831" alt="image" src="https://github.com/huajian123/ng-ant-admin/assets/31737260/639dfc1c-4805-427c-878b-56c98ea52447">
<img width="783" alt="image" src="https://github.com/huajian123/ng-ant-admin/assets/31737260/f5fe8180-0bd8-46d3-b6fa-7f2f944221b8">

**Comment by huajian123** [comment]
@factorx22 If you have any questions, please reopen this issue
