### ISSUE TITLE
带选择框的表格如何按条件设值禁用？

### ISSUE THREAD

**Issue by xia930425** [huajian123/ng-ant-admin#34]
![image](https://github.com/huajian123/ng-ant-admin/assets/78598847/c3666376-b571-4752-b118-1c4e22e2e5b3)
如图，应该如何传递条件参数，禁用符合条件的checkbox?

**Comment by huajian123** [comment]
@xia930425 Hi感谢你的issues
1. 在ant-table.component.html
![image](https://github.com/huajian123/ng-ant-admin/assets/31737260/92d9fedf-f860-48d7-b68e-91fd2a7660ee)
2. 在你的业务组件中，按钮方法中根据数据索引启用禁选，如果不满足你的需求，你可以自行修改：
![image](https://github.com/huajian123/ng-ant-admin/assets/31737260/dfdba93a-4fb8-4239-89d8-07e3d9a4e606)

**Comment by huajian123** [comment]
@xia930425 有任何疑问，请重新打开此issue
