### ISSUE TITLE
[question] modal outside component How can I pass an entire row of data instead of just an ID?

### ISSUE THREAD

**Issue by khanhtungmtp** [huajian123/ng-ant-admin#35]
I want to pass all the data of the selected row to a child component for editing, please guide me on how to do this, thank you very much.  image https://i.imgur.com/rovwAMR.png

**Comment by huajian123** [comment]
@khanhtungmtp Click on the selected data in the table and edit it through modal. You can refer to the component account.component.ts
![image](https://github.com/huajian123/ng-ant-admin/assets/31737260/798c3459-7157-4243-969d-3ea3f149f9da)

and in account-modal.component.ts,you can use nzModalData to get it

**Comment by khanhtungmtp** [comment]
Which library module does the show function belong to? I only see the create method. 
code here https://yamcode.com/formcomponentts and https://yamcode.com/maincomponentts-and-maincomponenthtml

> @khanhtungmtp Click on the selected data in the table and edit it through modal. You can refer to the component account.component.ts ![image](https://private-user-images.githubusercontent.com/31737260/323038586-798c3459-7157-4243-969d-3ea3f149f9da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMTkwMTMsIm5iZiI6MTcxMzMxODcxMywicGF0aCI6Ii8zMTczNzI2MC8zMjMwMzg1ODYtNzk4YzM0NTktNzE1Ny00MjQzLTk2OWQtM2VhM2YxNDlmOWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDAxNTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0M2QwM2Q4OTk3ZTg2MzZlYzNjNTQzOWQzZDFmNzg0NWU3OWYzNzkyN2JiYTAyZGI5MDE0NDNjMGQ2NjdiNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JlNErxBMio0M5o9QY27lvymuElF9gEFrzIOncOsAsGA)
> 
> and in account-modal.component.ts,you can use nzModalData to get it

**Comment by khanhtungmtp** [comment]
https://i.imgur.com/T18NJpC.png

**Comment by huajian123** [comment]
Do not use the modals provided by Zorro, please use the modals I provided. Please refer to the file in my project path of src/app/pages/system/account/account. component. ts as a reference, and track the source of the modalService attribute. You can refer to the content of the add() and edit() methods to call modal.
The directory path of the called module is src/app/widget/biz widget/system/account module
In this directory file, the nzModalData attribute in the account modal. component. ts file can be called from the following location, for example: 
![image](https://github.com/huajian123/ng-ant-admin/assets/31737260/9f24a1a9-b1fc-4feb-a01f-1a8a25b6ed88)

Transferred by the res here

**Comment by huajian123** [comment]
@khanhtungmtp You need to refer to the file src/app/widget/biz widget/system/account modal/account modal. service. ts for the show function to create your own file

**Comment by khanhtungmtp** [comment]
> @khanhtungmtp You need to refer to the file src/app/widget/biz widget/system/account modal/account modal. service. ts for the show function to create your own file

Ah, I want to pre-fetch the data on the main page and carry it over to the form page directly. As for having to get the API again, I've already passed the ID to the form and got the API on the form side. I'd like to use this method to reduce the calls to the API for getting details.

**Comment by huajian123** [comment]
The first method:
<img width="923" alt="image" src="https://github.com/huajian123/ng-ant-admin/assets/31737260/dc917749-75ce-46a2-b93a-1f0ffce6eb2f">
The second method:
change file src/app/shared/components/ant-table/ant-table.component.html
<img width="1126" alt="image" src="https://github.com/huajian123/ng-ant-admin/assets/31737260/e5f8cd34-19da-4842-962e-ce2ab7c02d9e">
and 
<img width="1114" alt="image" src="https://github.com/huajian123/ng-ant-admin/assets/31737260/463955b9-00f5-454f-b5a0-50eabade486d">
<img width="901" alt="image" src="https://github.com/huajian123/ng-ant-admin/assets/31737260/db5354d0-7655-471c-bf38-78b9181034bd">
I think both approaches are bad. Other users may modify the table data, causing the data you get to be lagging data. I think you should call the interface to get the data details when fetching the data, and then perform subsequent operations.

**Comment by huajian123** [comment]
@khanhtungmtp My latest code has expanded this ability, please refer to

**Comment by huajian123** [comment]
https://github.com/huajian123/ng-ant-admin/commit/3e1cbd5efa9b131ceebfa13da44d060f566c5da8

**Comment by khanhtungmtp** [comment]
thanks

**Comment by huajian123** [comment]
If you have any questions, please reopen this issue
