### ISSUE TITLE
modal error when edit

### ISSUE THREAD

**Issue by khanhtungmtp** [huajian123/ng-ant-admin#36]
I cloned from GitHub and tested the edit function at the "default/system/menu" path, and whether I press confirm or cancel, there's an error as shown in the picture. How can I fix it? I followed the guide to implement a similar function and encountered the same error.  see error on image:  https://i.imgur.com/rUz6NAM.png

**Comment by huajian123** [comment]
Please pull the latest code. I submitted the latest mock data yesterday. I don’t have such a problem locally now.

**Comment by khanhtungmtp** [comment]
I've pulled the latest updates, but I'm still encountering the error.   https://i.imgur.com/4oDRheE.png

**Comment by khanhtungmtp** [comment]
Oh, it's resolved now, but the code I followed to get the actual API is returning undefined. Not sure what's wrong now. Let me send you the code.

**Comment by khanhtungmtp** [comment]
https://i.imgur.com/kPUQl4g.png ,  https://i.imgur.com/1tIfHCt.png, https://i.imgur.com/Jua4Gex.png

**Comment by khanhtungmtp** [comment]
video error https://drive.google.com/file/d/1Lno68apdH_7A0vVpZ943scDNOJ1RYN7w/view?usp=sharing

**Comment by huajian123** [comment]
![image](https://github.com/huajian123/ng-ant-admin/assets/31737260/c0aa53bf-e882-4d95-8dfa-d89ec85b8944)
I can't reproduce this problem locally

**Comment by khanhtungmtp** [comment]
https://i.imgur.com/NODVWHg.png ,  https://i.imgur.com/JfMCvV3.png   After I pressed the confirm button, it encountered an error so it didn't proceed to that console.log line in the edit.

**Comment by khanhtungmtp** [comment]
> ![image](https://private-user-images.githubusercontent.com/31737260/324772051-c0aa53bf-e882-4d95-8dfa-d89ec85b8944.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjQ4NzcsIm5iZiI6MTcxMzg2NDU3NywicGF0aCI6Ii8zMTczNzI2MC8zMjQ3NzIwNTEtYzBhYTUzYmYtZTg4Mi00ZDk1LThkZmEtZDg5ZWM4NWI4OTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA5MjkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMmI1ZDE1NzU1ZWI1ZDQwNDgyZGYxNGZkMDMxMDBmYzIxNjU3ODc5N2QyZmQzNzFmMzhhMjg3N2ZiMGViNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KWRI8XqUhAVI2NjGna0dAPdZZIScRQn5RY0WlJiZBXA) I can't reproduce this problem locally

my code https://github.com/khanhtungmtp/BasecoreAdmin/commit/95204b0eeb015d6b3fb216775ffdb39de9515cc4

**Comment by huajian123** [comment]
src/app/widget/base-modal.ts line 37
try set
"  protected bsModalService = inject(NzModalService);"
to
"  protected bsModalService: NzModalService;"

**Comment by khanhtungmtp** [comment]
Not working :(((

**Comment by khanhtungmtp** [comment]
I tried console.logging your code and it does produce a modalRef, but when I console.log my code, that part doesn't appear. 
[![image](https://github.com/huajian123/ng-ant-admin/assets/42717112/f35e3327-6efa-4a45-a3c9-cfcac85dbd2a)](https://i.imgur.com/lrTPcHE.png)

**Comment by huajian123** [comment]
You can try to use zorro's modal, re-implement a case of using the service method to open the modal, modify the OnClick method in nzFooter, and see if you can get this input parameter.
https://ng.ant.design/components/modal/zh

**Comment by khanhtungmtp** [comment]
Using the default NzModal from Zorro, I've used it before, but because your custom modal has drag and fullscreen features, I opted for your custom modal. Anyway, thank you

**Comment by khanhtungmtp** [comment]
Oops, I found the error. It's because I deleted the constructor. I saw VSCode warning that the variable 'modalref' was never read, so I deleted it to clean up the code. But then it caused an error when I deleted it. Haha, thank you for your attention to my error. Thanks a lot. https://i.imgur.com/lp6JMLR.png
