### ISSUE TITLE
[question] form modal validation

### ISSUE THREAD

**Issue by khanhtungmtp** [huajian123/ng-ant-admin#37]
Can you tell me about the modal behavior? Is there a way to prevent the modal form from closing when a user enters an incorrect email format? It seems quite inconvenient to force users to reopen the modal and re-enter the information if they only made a mistake in the email field. https://i.imgur.com/v1QnSwY.png

**Comment by huajian123** [comment]
<img width="1313" alt="image" src="https://github.com/huajian123/ng-ant-admin/assets/31737260/9e5a7d8d-9517-42f3-aa0a-16a7bd0203f6">
Refer to here

**Comment by khanhtungmtp** [comment]
thanks
