### ISSUE TITLE
[question]  Warning: The animation trigger "tabSwitchMotion"

### ISSUE THREAD

**Issue by khanhtungmtp** [huajian123/ng-ant-admin#38]
![Untitled](https://github.com/huajian123/ng-ant-admin/assets/42717112/2d10dc2c-e371-4d25-872a-d78ddb34a82f)
![warning1](https://github.com/huajian123/ng-ant-admin/assets/42717112/6349739c-5edf-40b4-b7d2-39211919fa22)
Can you help me understand why this warning appears on [localhost](https://localhost/) but doesn’t on the server that's currently running, is it because it only shows warnings before the source code is published? It's quite confusing to look at.

**Comment by huajian123** [comment]
![image](https://github.com/huajian123/ng-ant-admin/assets/31737260/1a9f9474-5000-4cb1-b8a0-71b0ad409d95)
This could be a warning from zorro

**Comment by khanhtungmtp** [comment]
Thanks 😅
