### ISSUE TITLE
reuse-strategy.ts 有一处判断不合理

### ISSUE THREAD

**Issue by AlanLuo-dev** [huajian123/ng-ant-admin#39]
![微信截图_20240503172439](https://github.com/huajian123/ng-ant-admin/assets/35752648/eb5d402a-81a8-4643-b5fe-daa5403aa31f)

判断comp == null 应该写在 comp.instance之前，否则可能会 null.instance

**Comment by huajian123** [comment]
谢谢，已修复

**Comment by huajian123** [comment]
如果有任何问题，请重新打开此issue
