### ISSUE TITLE
[question] ant table checkbox item issue

### ISSUE THREAD

**Issue by khanhtungmtp** [huajian123/ng-ant-admin#40]
Let me ask, is it true that if the database returns without an id, then the checkbox item does not work, right? I see that if the database does not have an id, it errors when checking one box but it ends up checking all of them.  see video https://drive.google.com/file/d/1fotvNUzGZsJtr9FkleBvFFb1hWSXUAIO/view?usp=sharing

**Comment by huajian123** [comment]
Yes, I think each table data needs to have a unique id
<img width="1663" alt="image" src="https://github.com/huajian123/ng-ant-admin/assets/31737260/b0ccd8fb-76b2-444b-ab65-1883b775482b">
You can replace the id with the only attribute in your table in the picture below
<img width="1005" alt="image" src="https://github.com/huajian123/ng-ant-admin/assets/31737260/f2297e1b-66a5-4454-9064-4101c964c560">

**Comment by khanhtungmtp** [comment]
thanks
