### ISSUE TITLE
客服对话框，无法关闭

### ISSUE THREAD

**Issue by Edwin-WB-Li** [huajian123/ng-ant-admin#44]
客服对话框，开启后，关闭按钮遮挡了，关闭不了

**Comment by huajian123** [comment]
请提供截图

**Comment by Edwin-WB-Li** [comment]
<img width="953" alt="Snipaste_2024-08-08_11-15-25" src="https://github.com/user-attachments/assets/5282504b-cf7c-4d3a-8f63-822d8d9e80fa">

@huajian123

**Comment by huajian123** [comment]
这个是不是吧浏览器纵向收缩了

**Comment by Edwin-WB-Li** [comment]
> 这个是不是吧浏览器纵向收缩了

我这个是笔记本，可能屏幕有小，显示效果就是这样的

@huajian123

**Comment by Edwin-WB-Li** [comment]
还想请问一下，新增了一个页面为啥没有显示，难道需要通过脚手架生成才行？直接在原有基础上添加一个页面不行吗？

@huajian123

**Comment by huajian123** [comment]
脚手架的作用就是帮你在原基础上添加页面，只是不需要手动添加了，手动添加的话需要你对angular有一定的理解，建议从pure版本上手开始，手动添加页面

**Comment by Edwin-WB-Li** [comment]
> 脚手架的作用就是帮你在原基础上添加页面，只是不需要手动添加了，手动添加的话需要你对angular有一定的理解，建议从pure版本上手开始，手动添加页面

这个最新版本的，能不能手动添加？只能脚手架添加页面是吗？

**Comment by huajian123** [comment]
可以手动添加，配置好权限，路由，菜单，就可以了

**Comment by Edwin-WB-Li** [comment]
> 可以手动添加，配置好权限，路由，菜单，就可以了



奇怪，貌似都已经配置了，但好像菜单没显示出来，用路由跳转，也是显示没有权限
<img width="960" alt="Snipaste_2024-08-09_16-14-24" src="https://github.com/user-attachments/assets/bc4390e5-0320-4020-90bc-c0aba9dc492a">
<img width="956" alt="2" src="https://github.com/user-attachments/assets/cb983427-d8b9-4bcb-9548-56dc84aed16d">
<img width="960" alt="3-1" src="https://github.com/user-attachments/assets/0ece59ac-ed02-4c44-9c93-0b77e7153e19">
<img width="959" alt="3-2" src="https://github.com/user-attachments/assets/00b1b14a-ad24-4867-9cb4-160c7ecf5afc">

**Comment by huajian123** [comment]
登陆的时候会返回token，要从token中解析出用户拥有的权限，我的代码中，token是写死的

**Comment by huajian123** [comment]
如果有其他问题，请重新打开issue
