### ISSUE TITLE
系统管理--》菜单管理--》部门管理 ---》权限按钮

### ISSUE THREAD

**Issue by Edwin-WB-Li** [huajian123/ng-ant-admin#45]
<img width="784" alt="1" src="https://github.com/user-attachments/assets/190b18cc-95e3-4d84-9e6c-6f5a2acf7b09">

这些按钮权限有啥意义，貌似不起作用呀，我试着在数据库中修改了，Role，这里应该不会影响页面按钮权限的？

**Comment by huajian123** [comment]
1. 如果你有启动我的java服务端的话，大概需要退出登陆，然后重新登录。
2. 如果你没有启动java服务端的话，我目前前端的所有数据都是采用前端mock的，正在做nestjs的服务端

**Comment by Edwin-WB-Li** [comment]
> 1. 如果你有启动我的java服务端的话，大概需要退出登陆，然后重新登录。
> 2. 如果你没有启动java服务端的话，我目前前端的所有数据都是采用前端mock的，正在做nestjs的服务端

好的，谢谢讲解

**Comment by huajian123** [comment]
有任何疑问，请重新打开此issue
