### ISSUE TITLE
BasicConfirmModalComponent

### ISSUE THREAD

**Issue by foticc** [huajian123/ng-ant-admin#46]
BasicConfirmModalComponent继承这个类的对话框，确认按钮带loading功能怎么实现呢

**Comment by huajian123** [comment]
你是指在按钮上loading，还是点击按钮以后整个屏幕有个loading状态？
如果是前者的话，你可能要自定义footer来实现，自定义一个loading的按钮，如果是后者，可以参考src/app/widget/biz-widget/login/login-modal.component.ts，这里的getCurrentValue方法，这是一个异步函数，可以在这个函数内添加全屏loading

**Comment by foticc** [comment]
是按钮上loading，全屏的好像也可以,主要是想防止重复点击提交表单。多谢
