### ISSUE TITLE
添加新菜单报错,menu 的id没设值

### ISSUE THREAD

**Issue by foticc** [huajian123/ng-ant-admin#47]
[Nest] 12592  - 2024/12/17 16:56:48   ERROR [ExceptionsHandler] null value in column "id" of relation "menu" violates not-null constraint
error: null value in column "id" of relation "menu" violates not-null constraint

**Comment by huajian123** [comment]
@foticc 感谢，已修正

**Comment by huajian123** [comment]
@foticc hi 如果有任何其他问题，请重新打开此issue
