### ISSUE TITLE
下载后编译报错：node_modules/@antv/g2plot/lib/plots/venn/types.d.ts:10:18 - error TS2430: Interface 'VennOptions' incorrectly extends interface 'Options'

### ISSUE THREAD

**Issue by wen2204** [huajian123/ng-ant-admin#6]
Error: node_modules/@antv/g2plot/lib/plots/venn/types.d.ts:10:18 - error TS2430: Interface 'VennOptions' incorrectly extends interface 'Options'.
  Types of property 'color' are incompatible.
    Type 'string | string[] | ((datum: Datum, defaultColor: string) => string) | undefined' is not assignable to type 'ColorAttr | undefined'.
      Type '(datum: Datum, defaultColor: string) => string' is not assignable to type 'ColorAttr | undefined'.
        Type '(datum: Datum, defaultColor: string) => string' is not assignable to type '(datum: Datum, defaultColor?: string | undefined) => string'.
          Types of parameters 'defaultColor' and 'defaultColor' are incompatible.
            Type 'string | undefined' is not assignable to type 'string'.
              Type 'undefined' is not assignable to type 'string'.

看起来是包的问题，更新了版本也不行，是项目问题了？

**Comment by huajian123** [comment]
请确定一下angular版本是不是12和nodejs版本是不是14.x

**Comment by wen2204** [comment]
![err](https://user-images.githubusercontent.com/37831325/144708224-1c5ee629-e273-429b-aca2-b510c9ebf796.PNG)
确认过了，版本没问题

**Comment by huajian123** [comment]
你好，我重新拉去了最新master版本代码，安装依赖并且启动，并未发现你所说的情况。请尝试锁定@antv/g2plot的版本为2.3.36，如果还是报错，重新拉取master代码，安装依赖进行尝试

**Comment by wen2204** [comment]
我单独测了一下这个@antv/g2plot，也是报错，不是项目问题，是@antv/g2plot的问题
