### ISSUE TITLE
标签页样式

### ISSUE THREAD

**Issue by Etran-H** [huajian123/ng-ant-admin#9]
标签页样式调整一下会不会更好？
![image](https://user-images.githubusercontent.com/34226782/155244219-7c9a40f9-f38e-4caa-8130-903f3c9511b9.png)

当前
![image](https://user-images.githubusercontent.com/34226782/155244298-ca074beb-9188-43b8-91ff-a61524fbd80e.png)

**Comment by huajian123** [comment]
@Etran-H 您好，我是认为x图标离远一点，可以防止误触，您认为呢

**Comment by Etran-H** [comment]
抱歉，描述的不清楚，主要是header 和标签页之间的部分和标签页背景的颜色和padding 。
![image](https://user-images.githubusercontent.com/34226782/155289223-f2f80fbb-8e7c-4441-96eb-56434afb96b3.png)

**Comment by huajian123** [comment]
hi,我感觉我原来的还行，/笑哭

**Comment by Etran-H** [comment]
![image](https://user-images.githubusercontent.com/34226782/155934669-9365a457-8124-4187-a663-209c4b48d34d.png)
我理解下来层次关系是这样的；
第二层的卡片和标签页之间紧贴在一起，两个视觉单元之间没有间距是不是不太合理？
我在ant design 的组件中没有发现类似的用法。
为了保持简洁，我建议直接合并一二层，将标签页直接作为底层之上的层级。

**Comment by huajian123** [comment]
@Etran-H Hi，您可以根据自己的需求进行修改的

**Comment by huajian123** [comment]
@Etran-H Hi 现在已经添加固定标签模式，您可以看一下
